### ISSUE TITLE
API to add a pinning bot to lunet

### ISSUE THREAD

**Issue by Gozala** [Gozala/lunet#12]
## Goals

- Use may want to pin data in the remote IPFS node for availability.

## Proposed solution

At the moment dealing with UI is probably not the best use of our time. Instead we can create special URL pattern such that navigating to it would add a pinning bot to the lunet. e.g.

```
https://lunet.link/@invite/pinbot/https://mypinningbot.sh?token=apiAccessToken
```

Above will add pinning service with a name `pinbot` to the registry. On pin requests it would issue request to the provided url `https://mypinningbot.sh?token=apiAccessToken` and pass API access token via query argument.

Lunet will not know when user wishes to pin data there. In long term app will issue request to lunet triggering share user interaction, where user will be able to choose who (bot or person) to share with. But in the meantime we could introduce yet another URL pattern to address that e.g.

```
https://lunet.link/peerdium.gozala.io/${CID}@pinbot/`
```

Could tell lunet to load `CID` document into `peerdium.gozala.io` and pin all PUT requests into service named `@pinbot`.

**Comment by Gozala** [comment]
## TODO

Look at the existing pinning service APIs ideally it should be possible to encode them as pinbots

- [ ] https://github.com/textileio/textile-go/wiki/REST-API
- [ ] https://pinata.cloud/documentation#PinHashToIPFS
- [ ] https://www.eternum.io/help/api/
